[package]
name = "kataRUST-launcher"
version = "0.1.0"
authors = ["Steele Scott <steele@steele.gg>" , "Tyler Hill <tyler@oxide.fi>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "0.6.5"
attohttpc = "0.17.0"
litcrypt = "0.2.1"
base64 = "0.13.0"

[target.'cfg(target_os="windows")'.build-dependencies]
winres = "0.1.11"